### ISSUE TITLE
Determine board outline

### ISSUE THREAD

**Issue by glennl** [oresat/oresat-antenna#3]
Follow CDS 13

https://static1.squarespace.com/static/5418c831e4b0fa4ecac1bacd/t/56e9b62337013b6c063a655a/1458157095454/cds_rev13_final2.pdf

* Solar cells?
* Other antennas?
* GPS Patch
* S Band Patch
* Mechanical details
* This is done in Eagle

**Comment by andrewgreenberg** [comment]
Old issue, doesn't apply, closing.
